name: Publish documentation

on:
  push:
    branches: ["release"]

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  linting:
    uses: ./.github/workflows/pre-commit.yml

  build-docs:
    uses: ./.github/workflows/build_docs.yml

  run-tests:
    uses: ./.github/workflows/test_stable.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [build-docs, run-tests]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download docs artifact
        uses: actions/download-artifact@v6
        with:
          name: documentation
          path: "./documentation"

      - name: Upload page artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "./documentation"

      - name: Deploy coverage report to GH Pages
        id: deployment
        uses: actions/deploy-pages@v4
