name: Pre-commit

on:
  push:
    # The CI is executed on every push on every branch
    branches:
      - main
      - release
  pull_request:
    # The CI is executed on every pull request to the main branch
    branches:
      - main
  workflow_call:
  workflow_dispatch:

  schedule:
    # The CI is executed every day at 8am
    - cron: "0 8 * * *"

jobs:
  check-code:
    runs-on: ubuntu-22.04
    steps:
      # This action sets the current path to the root of your github repo
      - uses: actions/checkout@v5

      - name: Install pre-commit
        run: python3 -m pip install pre-commit

      - name: Run hooks
        run: pre-commit run --all
