name: Test package against stable release

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

  schedule:
    - cron: "30 8 * * 1"

jobs:
  test-code:
    runs-on: ubuntu-22.04
    container: ghcr.io/fenics/dolfinx/dolfinx:stable
    env:
      DEB_PYTHON_INSTALL_LAYOUT: deb_system

    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Install package
        run: python3 -m pip install .[test]

      - name: Run tests
        run: python3 -m pytest -vs
